### ISSUE TITLE
可以支持针对图片的大小或是缩放，而不是通过css统一设置吗？

### ISSUE THREAD

**Issue by lignpeng** [maqi1520/mdx-notes#83]
诉求：在文档中有许多的图片，但是通过css的设置不完美，因为有的图片很大、而有的图片很小，统一的尺寸会导致图片被拉伸的很厉害，影响美观。所以，想能不能支持对图片设置的支持，我尝试了但是不支持，希望可以支持一下。

比如支持：
！[]{height="50%" width="50%"}或者zoom=“50%”
或者：img  width="50%" height="50%">或<img src="" zoom="50%"

支持自定义图片大小话，我觉得会很棒

**Comment by lignpeng** [comment]
我调试发现：
1、使用如`<img src="./media/image35.png" width="100" height="150" />`，显示的是一个图标，没有图片内容。原因是：转换成了这个地址http://tauri.localhost/media/image35.png，因为是本地图片自然就无法加载了。

2、使用网络图片是可以正常显示以及设置大小
`<img src="https://picsum.photos/200/300" width="100" height="150" />`

3、而使用`![](./media/image35.png)`，可以正常显示，可以显示的原因是转换成了本地地址：http://asset.localhost/E:\markdown/media/image35.png，也就可以展示，但是无法设置图片的大小。

所以，能否优化一下，使得支持本地图片设置大小。

**Comment by lignpeng** [comment]
可以不用改了，哈哈哈，我已经实现了设置图片大小，自测完全OK。走，吃饭去了
`
//1、本地域名
localardass = 'http://asset.localhost/'

//2、可以设置全局的文件夹路径，这样方便图片使用相对路径了
global_dir = 'E:\\markdown/'

//3、拼接出本地图片完整的URL
function imgPath(src, defaultPath = '') {
  if(src.includes('https://') || src.includes("http://")){
    return src
  }

  var path = defaultPath
  let isHasdir = src.includes(':\\')
  if (global_dir !== '' && path === '' && !isHasdir) {
    path = global_dir
  }
  d = localardass + path + src
  return d
}

function Imgs({ src, width = '100%', height = '100%', defaultPath = '' }) {
  return (
    <div className="cosimg">
      <img src={imgPath((src = src), (defaultPath = defaultPath))} width={width} height={height} />
    </div>
  )
}
`
使用：
`
---
title: 图片设置
theme:lx
---

1、给全局变量设置了文件夹，所以只要配图片的相对路径即可
global_dir = 'E:\\markdown/'

<Imgs src="media/image35.png" width="100%" height="100%" />

2、指定文件夹路径
<Imgs src="media/image35.png" defaultPath='E:\\markdown/' width="100%" height="100%" />

3、可以直接设置图片的完整路径
<Imgs src="E:\\markdown/media/image35.png" width="100%" height="100%" />
4、自己拼接完整url
<Imgs src="http://asset.localhost/E:\\markdown/media/image35.png" width="100" height="150" />

5、网络图片
<Imgs src="https://picsum.photos/200/300" width="100" height="150" />

`

**Comment by maqi1520** [comment]
推荐使用相对路径，就是图片是存在当前工作目录的

<img width="1194" alt="CleanShot_2024_10_26_at_22 17 17@2x" src="https://github.com/user-attachments/assets/f003b8e2-b0c7-40b9-bb00-7ce80db58825">

缩放的我找时间，实现下

**Comment by maqi1520** [comment]
可以通过下载 [v1.0.2](https://github.com/maqi1520/mdx-notes/releases/tag/v1.0.2)
语法同 obsidian

<img width="1312" alt="CleanShot_2024_10_27_at_11 26 46@2x" src="https://github.com/user-attachments/assets/067c624e-eac5-4e59-9b7c-1569e096470c">

```md
![title|50%](/img/1.png)
![title|50](/img/1.png)
![title|100x100](/img/1.png)
![](/img/1.png)

```
